# Site wide configuration

title:  adithya-potlapelli.github.io         
locale: en_US
url: https://adithya-potlapelli.github.io/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Adithya Potlapelli
  avatar: ap-logo.png
  position: Software Developer 2
  school: 
  place: Hyderabad, India
  bio:
  email: 
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: adithya-potlapelli #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: adithya-potlapelli #username
  xing: #username
  medium: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  scholar: #username

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
